### ISSUE TITLE
Issues wrap-up / prelaunch

### ISSUE THREAD

**Issue by furilo** [TrackDons/trackdons#130]
Hey, some things so we can do a proper prelaunch. To discuss, we can change/postpone things.

- [x] Include textarea for comment in donation edit #129
- [x] Post-donation comment #128
- [ ] Finish Responsive for donation form #112 
- [x] Profile page: don't show total amount #117 
- [x] How to show recurring donations #116 
- [ ] Friends activity #127

Optional: 

- [ ] Set up ahoy app #104 

For a next iteration: 

- [ ] Email alert when a friend creates a donation #131
- [ ] Follow button in user profile
- [ ] Issues #72
