### ISSUE TITLE
First pseudo-public release?

### ISSUE THREAD

**Issue by furilo** [TrackDons/trackdons#26]
Should we try to do a first friends-release? List here what things you consider needed to do it: 

- [x] Register domain (we have trackdon[s].[org|com]
- [x] Decide how to release #27
- [x] Set up production environment #25
- [x] Close #6 New Donation: Use gem Select2
- [x] Close #44 When adding a donation, if project creation needed, display mandatory fields for new project inline
- [x] Close #36 Fix basic responsive issues
- [x] Close #11 Add permalink donation
- [x] Close #24 Edit & remove donations
- [x] Close #13 Add a language switcher
- [x] Close #31 Finish languages for launch
